#------------------------------------------------------------------------------#
# This makefile was generated by 'cbp2make' tool rev.147                       #
#------------------------------------------------------------------------------#


WORKDIR = `pwd`

CC = gcc
CXX = g++
AR = ar
LD = g++
WINDRES = windres

INC = 
CFLAGS = -Wall
RESINC = 
LIBDIR = 
LIB = 
LDFLAGS = 

INC_DEBUG = $(INC)
CFLAGS_DEBUG = $(CFLAGS) -std=c99 -g `pkg-config gtk+-3.0 --cflags`
RESINC_DEBUG = $(RESINC)
RCFLAGS_DEBUG = $(RCFLAGS)
LIBDIR_DEBUG = $(LIBDIR)
LIB_DEBUG = $(LIB)
LDFLAGS_DEBUG = $(LDFLAGS) `pkg-config gtk+-3.0 --libs`
OBJDIR_DEBUG = obj/Debug
DEP_DEBUG = 
OUT_DEBUG = bin/Debug/nomad

INC_RELEASE = $(INC)
CFLAGS_RELEASE = $(CFLAGS) -O2 -std=c99 `pkg-config gtk+-3.0 --cflags`
RESINC_RELEASE = $(RESINC)
RCFLAGS_RELEASE = $(RCFLAGS)
LIBDIR_RELEASE = $(LIBDIR)
LIB_RELEASE = $(LIB)
LDFLAGS_RELEASE = $(LDFLAGS) -s `pkg-config gtk+-3.0 --libs`
OBJDIR_RELEASE = obj/Release
DEP_RELEASE = 
OUT_RELEASE = bin/Release/nomad

OBJ_DEBUG = $(OBJDIR_DEBUG)/GPX_parse.o $(OBJDIR_DEBUG)/analysis.o $(OBJDIR_DEBUG)/main.o $(OBJDIR_DEBUG)/parse_double.o $(OBJDIR_DEBUG)/window.o

OBJ_RELEASE = $(OBJDIR_RELEASE)/GPX_parse.o $(OBJDIR_RELEASE)/analysis.o $(OBJDIR_RELEASE)/main.o $(OBJDIR_RELEASE)/parse_double.o $(OBJDIR_RELEASE)/window.o

all: debug release

clean: clean_debug clean_release

before_debug: 
	test -d bin/Debug || mkdir -p bin/Debug
	test -d $(OBJDIR_DEBUG) || mkdir -p $(OBJDIR_DEBUG)

after_debug: 

debug: before_debug out_debug after_debug

out_debug: before_debug $(OBJ_DEBUG) $(DEP_DEBUG)
	$(LD) $(LIBDIR_DEBUG) -o $(OUT_DEBUG) $(OBJ_DEBUG)  $(LDFLAGS_DEBUG) $(LIB_DEBUG)

$(OBJDIR_DEBUG)/GPX_parse.o: GPX_parse.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c GPX_parse.c -o $(OBJDIR_DEBUG)/GPX_parse.o

$(OBJDIR_DEBUG)/analysis.o: analysis.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c analysis.c -o $(OBJDIR_DEBUG)/analysis.o

$(OBJDIR_DEBUG)/main.o: main.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c main.c -o $(OBJDIR_DEBUG)/main.o

$(OBJDIR_DEBUG)/parse_double.o: parse_double.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c parse_double.c -o $(OBJDIR_DEBUG)/parse_double.o

$(OBJDIR_DEBUG)/window.o: window.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c window.c -o $(OBJDIR_DEBUG)/window.o

clean_debug: 
	rm -f $(OBJ_DEBUG) $(OUT_DEBUG)
	rm -rf bin/Debug
	rm -rf $(OBJDIR_DEBUG)

before_release: 
	test -d bin/Release || mkdir -p bin/Release
	test -d $(OBJDIR_RELEASE) || mkdir -p $(OBJDIR_RELEASE)

after_release: 

release: before_release out_release after_release

out_release: before_release $(OBJ_RELEASE) $(DEP_RELEASE)
	$(LD) $(LIBDIR_RELEASE) -o $(OUT_RELEASE) $(OBJ_RELEASE)  $(LDFLAGS_RELEASE) $(LIB_RELEASE)

$(OBJDIR_RELEASE)/GPX_parse.o: GPX_parse.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c GPX_parse.c -o $(OBJDIR_RELEASE)/GPX_parse.o

$(OBJDIR_RELEASE)/analysis.o: analysis.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c analysis.c -o $(OBJDIR_RELEASE)/analysis.o

$(OBJDIR_RELEASE)/main.o: main.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c main.c -o $(OBJDIR_RELEASE)/main.o

$(OBJDIR_RELEASE)/parse_double.o: parse_double.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c parse_double.c -o $(OBJDIR_RELEASE)/parse_double.o

$(OBJDIR_RELEASE)/window.o: window.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c window.c -o $(OBJDIR_RELEASE)/window.o

clean_release: 
	rm -f $(OBJ_RELEASE) $(OUT_RELEASE)
	rm -rf bin/Release
	rm -rf $(OBJDIR_RELEASE)

.PHONY: before_debug after_debug clean_debug before_release after_release clean_release

